name: Update Gradle Wrapper

on:
  workflow_dispatch: # 手動実行を許可
  schedule:
    - cron: "0 0 1 * *" # 日本時間 (JST) 午前9時 (UTC+9)

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Prepare secrets.properties
        run: cp secrets.properties.sample secrets.properties

      - name: Prepare local.properties
        run: touch local.properties

      - name: Update Gradle Wrapper to latest
        run: |
          ./gradlew wrapper --gradle-version "latest"

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --exit-code --quiet gradle/wrapper/gradle-wrapper.properties; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
            echo "Gradle Wrapper is already up to date."
          else
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
            echo "Changes detected in gradle-wrapper.properties."
          fi

      - name: Generate branch name
        id: generate_branch_name
        if: steps.check_changes.outputs.no_changes == 'false'
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          echo "branch_name=feature/update-gradle-wrapper-${TIMESTAMP}" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: steps.check_changes.outputs.no_changes == 'false'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Update Gradle Wrapper to latest version"
          title: "chore: Update Gradle Wrapper to latest version"
          body: |
            Gradle Wrapper が最新バージョンに更新されました。
          branch: "${{ steps.generate_branch_name.outputs.branch_name }}"
          delete-branch: true
          labels: |
            dependencies
            automated pr
          reviewers: |
            maehata-fairy
